// Code generated by openapi-inventory; DO NOT EDIT.

package api

// OperationID 是公开契约中的稳定 operationId。
type OperationID string

// Operation 描述公开路由的低基数身份与策略。
type Operation struct {
	ID     OperationID
	Method string
	Path   string
	Policy string
	Scope  string
	Action string
}

const (
	OperationCompleteTodo OperationID = "completeTodo"
	OperationCreateTodo   OperationID = "createTodo"
	OperationGetTodo      OperationID = "getTodo"
	OperationListTodos    OperationID = "listTodos"
)

var operationInventory = [...]Operation{
	{ID: OperationCompleteTodo, Method: "PATCH", Path: "/api/v1/todos/{id}/complete", Policy: "protected", Scope: "todos:write", Action: "todo.complete"},
	{ID: OperationCreateTodo, Method: "POST", Path: "/api/v1/todos", Policy: "protected", Scope: "todos:write", Action: "todo.create"},
	{ID: OperationGetTodo, Method: "GET", Path: "/api/v1/todos/{id}", Policy: "protected", Scope: "todos:read", Action: "todo.read"},
	{ID: OperationListTodos, Method: "GET", Path: "/api/v1/todos", Policy: "protected", Scope: "todos:read", Action: "todo.list"},
}

// Operations 返回与生成代码解耦的 inventory 副本。
func Operations() []Operation {
	return append([]Operation(nil), operationInventory[:]...)
}

// OperationForStrictName 把 strict middleware 名称映射回原始 operationId。
func OperationForStrictName(name string) (Operation, bool) {
	switch name {
	case "CompleteTodo":
		return Operation{ID: OperationCompleteTodo, Method: "PATCH", Path: "/api/v1/todos/{id}/complete", Policy: "protected", Scope: "todos:write", Action: "todo.complete"}, true
	case "CreateTodo":
		return Operation{ID: OperationCreateTodo, Method: "POST", Path: "/api/v1/todos", Policy: "protected", Scope: "todos:write", Action: "todo.create"}, true
	case "GetTodo":
		return Operation{ID: OperationGetTodo, Method: "GET", Path: "/api/v1/todos/{id}", Policy: "protected", Scope: "todos:read", Action: "todo.read"}, true
	case "ListTodos":
		return Operation{ID: OperationListTodos, Method: "GET", Path: "/api/v1/todos", Policy: "protected", Scope: "todos:read", Action: "todo.list"}, true
	default:
		return Operation{}, false
	}
}
